spring:
  datasource:
    url: jdbc:mysql://192.168.9.200:3306/test?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bdqn
#  thymeleaf:
#    cache: false
#    mode: LEGACYHTML5
mybatis-plus:
  type-aliases-package: com.bdqn.pojo
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    com:
      bdqn:
        bookmanage:
          mapper : debug

server:
  #端口号
  port: 8888
          #配置日志
#  config: classpath:logback-boot.xml
#pagehelper:
#  helperDialect: mysql
##  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql


